In [1]:
import pandas as pd
import numpy as np

In [2]:
col_names = ["empty","T-Day","T-Month","T-Year", "Code", "No", "R-Day","R-Month","R-Year",
         "Origin Court", "Origin Code", "Origin No", "Origin Year", "Specific Case Type",
         "Judge 1", "Judge 2", "Judge 3", "Judge 4", "Judge 5", "Judge 6", "Judge 7", 
         "Case coming for", "Case OutCome", "Reason of adjournment", "N-Day","N-Month",
         "N-Year","P-M", "P-F","P-Org.", "D-M", "D-F", "D-Org.", "Legal Rep", "Witness-P", "Witness-D",
         "Crim-Custody","Other Details"]

In [3]:
sample_data = pd.read_excel("data/sample_data.xlsx", names = col_names)

In [4]:
sample_data.head()

,empty,T-Day,T-Month,T-Year,Code,No,R-Day,R-Month,R-Year,Origin Court,...,P-F,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details
0,NaN,Court station name: \n(Entry required.),NaN,NaN,A. N. Other,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN
2,NaN,\nToday's date\n\n\n\n\n\n,NaN,NaN,\nCase Number and date of Registration)\n\n,NaN,NaN,NaN,NaN,\n*Appeal cases only: ...,...,NaN,NaN,\nNo. of defendants/accused\n\n\n\n\n,NaN,NaN,\nDo any of the parties have legal representat...,\nNo. of witnesses testified in court today\n\n\n,NaN,"\nCriminal cases only: \nOf the accused, how m...",\nOther important details of the case
3,NaN,Day,Month,Year,Code,No.,Day,Month,Year,Name of Court,...,F,Org.,M,F,Org.,(Y/N),P \n(Enter No.),D\n(Enter No.),(Enter No.),(Free text)
4,NaN,3,Apr,2023,QRCR,E642,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN

In [5]:
sample_data.drop(index=range(0, 4), inplace=True)

In [6]:
sample_data.head(15)

,empty,T-Day,T-Month,T-Year,Code,No,R-Day,R-Month,R-Year,Origin Court,...,P-F,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details
4,NaN,3,Apr,2023,QRCR,E642,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
5,NaN,3,Apr,2023,QRCR,E1411,31,Oct,2022,NaN,...,NaN,1,1,NaN,NaN,No,NaN,1,0,NaN
6,NaN,3,Apr,2023,QRCR,E649,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
7,NaN,3,Apr,2023,QRCR,E638,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
8,NaN,3,Apr,2023,QRCRMISC,E109,3,Apr,2023,NaN,...,NaN,1,NaN,2,NaN,No,NaN,NaN,2,NaN
9,NaN,3,Apr,2023,QRCR,E637,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
10,NaN,3,Apr,2023,QRCR,E639,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,0,NaN
11,NaN,3,Apr,2023,QRCR,E643,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
12,NaN,3,Apr,2023,QRCRMISC,E107,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
13,NaN,3,Apr,2023,QRCR,34,6,Jan,2020,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,0,NaN
14,NaN,3,Apr,2023,QRCR,E361,14,Feb,2023,NaN,...,NaN,1,1,NaN,NaN,Yes,NaN,NaN,0,NaN
15,NaN,3,Apr,2023,QRCR,E481,6,Mar,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
16,NaN,3,Apr,2023,QRCR,E480,6,Mar,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
17,NaN,3,Apr,2023,QRSO,E031,3,Mar,2022,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,0,NaN
18,NaN,3,Apr,2023,QRCR,E995,1,Aug,2022,NaN,...,NaN,1,NaN,1,NaN,No,NaN,NaN,0,NaN

In [7]:
sample_data.reset_index(drop=True, inplace=True)

In [8]:
sample_data.head(15)

,empty,T-Day,T-Month,T-Year,Code,No,R-Day,R-Month,R-Year,Origin Court,...,P-F,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details
0,NaN,3,Apr,2023,QRCR,E642,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
1,NaN,3,Apr,2023,QRCR,E1411,31,Oct,2022,NaN,...,NaN,1,1,NaN,NaN,No,NaN,1,0,NaN
2,NaN,3,Apr,2023,QRCR,E649,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
3,NaN,3,Apr,2023,QRCR,E638,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
4,NaN,3,Apr,2023,QRCRMISC,E109,3,Apr,2023,NaN,...,NaN,1,NaN,2,NaN,No,NaN,NaN,2,NaN
5,NaN,3,Apr,2023,QRCR,E637,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
6,NaN,3,Apr,2023,QRCR,E639,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,0,NaN
7,NaN,3,Apr,2023,QRCR,E643,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
8,NaN,3,Apr,2023,QRCRMISC,E107,3,Apr,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
9,NaN,3,Apr,2023,QRCR,34,6,Jan,2020,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,0,NaN
10,NaN,3,Apr,2023,QRCR,E361,14,Feb,2023,NaN,...,NaN,1,1,NaN,NaN,Yes,NaN,NaN,0,NaN
11,NaN,3,Apr,2023,QRCR,E481,6,Mar,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
12,NaN,3,Apr,2023,QRCR,E480,6,Mar,2023,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
13,NaN,3,Apr,2023,QRSO,E031,3,Mar,2022,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,0,NaN
14,NaN,3,Apr,2023,QRCR,E995,1,Aug,2022,NaN,...,NaN,1,NaN,1,NaN,No,NaN,NaN,0,NaN

In [9]:
sample_data.drop(columns=["empty"], inplace=True)

In [10]:
# create the column today days
sample_data["Today's Date"] = sample_data["T-Day"].astype(str) + "-" + sample_data["T-Month"] + "-" + sample_data["T-Year"].astype(str)

In [11]:
# concatenate t-dates
sample_data.head()

,T-Day,T-Month,T-Year,Code,No,R-Day,R-Month,R-Year,Origin Court,Origin Code,...,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details,Today's Date
0,3,Apr,2023,QRCR,E642,3,Apr,2023,NaN,NaN,...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,3-Apr-2023
1,3,Apr,2023,QRCR,E1411,31,Oct,2022,NaN,NaN,...,1,1,NaN,NaN,No,NaN,1,0,NaN,3-Apr-2023
2,3,Apr,2023,QRCR,E649,3,Apr,2023,NaN,NaN,...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,3-Apr-2023
3,3,Apr,2023,QRCR,E638,3,Apr,2023,NaN,NaN,...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,3-Apr-2023
4,3,Apr,2023,QRCRMISC,E109,3,Apr,2023,NaN,NaN,...,1,NaN,2,NaN,No,NaN,NaN,2,NaN,3-Apr-2023

In [12]:
# Convert to date
sample_data["Today's Date"] = pd.to_datetime(sample_data["Today's Date"], format='%d-%b-%Y')

In [13]:
sample_data.dtypes

T-Day                            object
T-Month                          object
T-Year                           object
Code                             object
No                               object
R-Day                            object
R-Month                          object
R-Year                           object
Origin Court                     object
Origin Code                      object
Origin No                        object
Origin Year                      object
Specific Case Type               object
Judge 1                          object
Judge 2                          object
Judge 3                          object
Judge 4                          object
Judge 5                          object
Judge 6                          object
Judge 7                          object
Case coming for                  object
Case OutCome                     object
Reason of adjournment            object
N-Day                            object
N-Month                          object
N-Year                           object
P-M                              object
P-F                              object
P-Org.                           object
D-M                              object
D-F                              object
D-Org.                           object
Legal Rep                        object
Witness-P                        object
Witness-D                        object
Crim-Custody                     object
Other Details                    object
Today's Date             datetime64[ns]
dtype: object

In [14]:
sample_data.drop(columns=["T-Day", "T-Month", "T-Year"], inplace=True)

In [15]:
sample_data.head()

,Code,No,R-Day,R-Month,R-Year,Origin Court,Origin Code,Origin No,Origin Year,Specific Case Type,...,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details,Today's Date
0,QRCR,E642,3,Apr,2023,NaN,NaN,NaN,NaN,"Burglary, housebreaking, entering dwelling-hou...",...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,2023-04-03
1,QRCR,E1411,31,Oct,2022,NaN,NaN,NaN,NaN,"Burglary, housebreaking, entering dwelling-hou...",...,1,1,NaN,NaN,No,NaN,1,0,NaN,2023-04-03
2,QRCR,E649,3,Apr,2023,NaN,NaN,NaN,NaN,Possession of narcotic drugs and psychotropic ...,...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,2023-04-03
3,QRCR,E638,3,Apr,2023,NaN,NaN,NaN,NaN,"Grievous harm, maim, assault causing actual bo...",...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,2023-04-03
4,QRCRMISC,E109,3,Apr,2023,NaN,NaN,NaN,NaN,Criminal Miscellaneous Application,...,1,NaN,2,NaN,No,NaN,NaN,2,NaN,2023-04-03

In [16]:
# change the positon of a new-column
sample_data.insert(0, "Today's Date", sample_data.pop("Today's Date"))

In [17]:
sample_data.head()

,Today's Date,Code,No,R-Day,R-Month,R-Year,Origin Court,Origin Code,Origin No,Origin Year,...,P-F,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details
0,2023-04-03,QRCR,E642,3,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
1,2023-04-03,QRCR,E1411,31,Oct,2022,NaN,NaN,NaN,NaN,...,NaN,1,1,NaN,NaN,No,NaN,1,0,NaN
2,2023-04-03,QRCR,E649,3,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
3,2023-04-03,QRCR,E638,3,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
4,2023-04-03,QRCRMISC,E109,3,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,1,NaN,2,NaN,No,NaN,NaN,2,NaN

In [18]:
sample_data["Registration Date"] = sample_data["R-Day"].astype(str) + "-" + sample_data["R-Month"] + "-" + sample_data["R-Year"].astype(str)

In [19]:
sample_data.tail()

,Today's Date,Code,No,R-Day,R-Month,R-Year,Origin Court,Origin Code,Origin No,Origin Year,...,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details,Registration Date
2152,2023-04-28,QRSUCCMISC,E085,19,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,1,NaN,NaN,Yes,NaN,NaN,0,NaN,19-Apr-2023
2153,2023-04-28,QRSUCCMISC,E074,6,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,No,NaN,NaN,0,NaN,6-Apr-2023
2154,2023-04-28,QRCC,E216,28,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,2,1,NaN,Yes,NaN,NaN,0,Certificate of urgency activity auto-created,28-Apr-2023
2155,2023-04-28,QRELCMISC,E009,27,Apr,2023,NaN,NaN,NaN,NaN,...,NaN,NaN,1,NaN,No,NaN,NaN,0,Certificate of urgency activity auto-created,27-Apr-2023
2156,2023-04-28,QRCC,24,24,Jan,2020,NaN,NaN,NaN,NaN,...,NaN,1,NaN,NaN,Yes,NaN,NaN,0,Certificate of urgency activity auto-created,24-Jan-2020

In [20]:
# Convert to date
sample_data["Registration Date"] = pd.to_datetime(sample_data["Registration Date"], format='%d-%b-%Y')

In [21]:
sample_data.drop(columns=["R-Day", "R-Month"], inplace=True)

In [22]:
# change the positon of a new-column
sample_data.insert(1, "Registration Date", sample_data.pop("Registration Date"))

In [23]:
sample_data["Case Number"] = sample_data["Code"].astype(str) + "/" + sample_data["No"].astype(str) + "/" + sample_data["R-Year"].astype(str)

In [24]:
sample_data.tail()

,Today's Date,Registration Date,Code,No,R-Year,Origin Court,Origin Code,Origin No,Origin Year,Specific Case Type,...,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details,Case Number
2152,2023-04-28,2023-04-19,QRSUCCMISC,E085,2023,NaN,NaN,NaN,NaN,Miscellaneous Succession,...,NaN,1,NaN,NaN,Yes,NaN,NaN,0,NaN,QRSUCCMISC/E085/2023
2153,2023-04-28,2023-04-06,QRSUCCMISC,E074,2023,NaN,NaN,NaN,NaN,Miscellaneous Succession,...,NaN,NaN,NaN,NaN,No,NaN,NaN,0,NaN,QRSUCCMISC/E074/2023
2154,2023-04-28,2023-04-28,QRCC,E216,2023,NaN,NaN,NaN,NaN,Liquidated Claim,...,NaN,2,1,NaN,Yes,NaN,NaN,0,Certificate of urgency activity auto-created,QRCC/E216/2023
2155,2023-04-28,2023-04-27,QRELCMISC,E009,2023,NaN,NaN,NaN,NaN,Environmental and Land Miscellaneous,...,NaN,NaN,1,NaN,No,NaN,NaN,0,Certificate of urgency activity auto-created,QRELCMISC/E009/2023
2156,2023-04-28,2020-01-24,QRCC,24,2020,NaN,NaN,NaN,NaN,Commercial Suits,...,NaN,1,NaN,NaN,Yes,NaN,NaN,0,Certificate of urgency activity auto-created,QRCC/24/2020

In [25]:
# change the positon of a new-column
sample_data.insert(2, "Case Number", sample_data.pop("Case Number"))

In [26]:
sample_data.drop(columns=["Code", "No", "R-Year"], inplace=True)

In [27]:
sample_data.tail()

,Today's Date,Registration Date,Case Number,Origin Court,Origin Code,Origin No,Origin Year,Specific Case Type,Judge 1,Judge 2,...,P-F,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details
2152,2023-04-28,2023-04-19,QRSUCCMISC/E085/2023,NaN,NaN,NaN,NaN,Miscellaneous Succession,Hon XYZ,NaN,...,NaN,NaN,1,NaN,NaN,Yes,NaN,NaN,0,NaN
2153,2023-04-28,2023-04-06,QRSUCCMISC/E074/2023,NaN,NaN,NaN,NaN,Miscellaneous Succession,Hon XYZ,NaN,...,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,0,NaN
2154,2023-04-28,2023-04-28,QRCC/E216/2023,NaN,NaN,NaN,NaN,Liquidated Claim,Hon XYZ,NaN,...,NaN,NaN,2,1,NaN,Yes,NaN,NaN,0,Certificate of urgency activity auto-created
2155,2023-04-28,2023-04-27,QRELCMISC/E009/2023,NaN,NaN,NaN,NaN,Environmental and Land Miscellaneous,Hon A N Other,NaN,...,NaN,NaN,NaN,1,NaN,No,NaN,NaN,0,Certificate of urgency activity auto-created
2156,2023-04-28,2020-01-24,QRCC/24/2020,NaN,NaN,NaN,NaN,Commercial Suits,Hon XYZ,NaN,...,NaN,NaN,1,NaN,NaN,Yes,NaN,NaN,0,Certificate of urgency activity auto-created

In [28]:
sample_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2157 entries, 0 to 2156
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Today's Date           2157 non-null   datetime64[ns]
 1   Registration Date      2157 non-null   datetime64[ns]
 2   Case Number            2157 non-null   object
 3   Origin Court           0 non-null      object
 4   Origin Code            0 non-null      object
 5   Origin No              0 non-null      object
 6   Origin Year            0 non-null      object
 7   Specific Case Type     2157 non-null   object
 8   Judge 1                2157 non-null   object
 9   Judge 2                0 non-null      object
 10  Judge 3                0 non-null      object
 11  Judge 4                0 non-null      object
 12  Judge 5                0 non-null      object
 13  Judge 6                0 non-null      object
 14  Judge 7                0 non-null      object
 15  Case coming for        2157 non-null   object
 16  Case OutCome           2157 non-null   object
 17  Reason of adjournment  156 non-null    object
 18  N-Day                  1639 non-null   object
 19  N-Month                1639 non-null   object
 20  N-Year                 1639 non-null   object
 21  P-M                    539 non-null    object
 22  P-F                    248 non-null    object
 23  P-Org.                 1425 non-null   object
 24  D-M                    1669 non-null   object
 25  D-F                    433 non-null    object
 26  D-Org.                 244 non-null    object
 27  Legal Rep              2157 non-null   object
 28  Witness-P              77 non-null     object
 29  Witness-D              25 non-null     object
 30  Crim-Custody           1697 non-null   object
 31  Other Details          506 non-null    object
dtypes: datetime64[ns](2), object(30)
memory usage: 539.4+ KB

In [29]:
sample_data.drop(columns=["Origin Court", "Origin Code", "Origin No", "Origin Year", "Judge 2", "Judge 3", "Judge 4", "Judge 5", "Judge 6", "Judge 7"], inplace=True)

In [30]:
sample_data.head()

,Today's Date,Registration Date,Case Number,Specific Case Type,Judge 1,Case coming for,Case OutCome,Reason of adjournment,N-Day,N-Month,...,P-F,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details
0,2023-04-03,2023-04-03,QRCR/E642/2023,"Burglary, housebreaking, entering dwelling-hou...",Hon A N Other,Plea,Mention date set (in court),NaN,12,Apr,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
1,2023-04-03,2022-10-31,QRCR/E1411/2022,"Burglary, housebreaking, entering dwelling-hou...",Hon XYZ,Hearing,Adjournment,Advocate not ready,24,Apr,...,NaN,1,1,NaN,NaN,No,NaN,1,0,NaN
2,2023-04-03,2023-04-03,QRCR/E649/2023,Possession of narcotic drugs and psychotropic ...,Hon A N Other,Plea,Mention date set (in court),NaN,12,Apr,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
3,2023-04-03,2023-04-03,QRCR/E638/2023,"Grievous harm, maim, assault causing actual bo...",Hon A N Other,Plea,Mention date set (in court),NaN,17,Apr,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
4,2023-04-03,2023-04-03,QRCRMISC/E109/2023,Criminal Miscellaneous Application,Hon A N Other,Certificate of urgency,Mention date set (in court),NaN,12,Apr,...,NaN,1,NaN,2,NaN,No,NaN,NaN,2,NaN

In [31]:
sample_data["Judicial Officer"] = sample_data["Judge 1"].astype(str)

In [32]:
sample_data.head()

,Today's Date,Registration Date,Case Number,Specific Case Type,Judge 1,Case coming for,Case OutCome,Reason of adjournment,N-Day,N-Month,...,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details,Judicial Officer
0,2023-04-03,2023-04-03,QRCR/E642/2023,"Burglary, housebreaking, entering dwelling-hou...",Hon A N Other,Plea,Mention date set (in court),NaN,12,Apr,...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,Hon A N Other
1,2023-04-03,2022-10-31,QRCR/E1411/2022,"Burglary, housebreaking, entering dwelling-hou...",Hon XYZ,Hearing,Adjournment,Advocate not ready,24,Apr,...,1,1,NaN,NaN,No,NaN,1,0,NaN,Hon XYZ
2,2023-04-03,2023-04-03,QRCR/E649/2023,Possession of narcotic drugs and psychotropic ...,Hon A N Other,Plea,Mention date set (in court),NaN,12,Apr,...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,Hon A N Other
3,2023-04-03,2023-04-03,QRCR/E638/2023,"Grievous harm, maim, assault causing actual bo...",Hon A N Other,Plea,Mention date set (in court),NaN,17,Apr,...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,Hon A N Other
4,2023-04-03,2023-04-03,QRCRMISC/E109/2023,Criminal Miscellaneous Application,Hon A N Other,Certificate of urgency,Mention date set (in court),NaN,12,Apr,...,1,NaN,2,NaN,No,NaN,NaN,2,NaN,Hon A N Other

In [33]:
sample_data.insert(4, "Judicial Officer", sample_data.pop("Judicial Officer"))

In [34]:
sample_data.head()

,Today's Date,Registration Date,Case Number,Specific Case Type,Judicial Officer,Judge 1,Case coming for,Case OutCome,Reason of adjournment,N-Day,...,P-F,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details
0,2023-04-03,2023-04-03,QRCR/E642/2023,"Burglary, housebreaking, entering dwelling-hou...",Hon A N Other,Hon A N Other,Plea,Mention date set (in court),NaN,12,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
1,2023-04-03,2022-10-31,QRCR/E1411/2022,"Burglary, housebreaking, entering dwelling-hou...",Hon XYZ,Hon XYZ,Hearing,Adjournment,Advocate not ready,24,...,NaN,1,1,NaN,NaN,No,NaN,1,0,NaN
2,2023-04-03,2023-04-03,QRCR/E649/2023,Possession of narcotic drugs and psychotropic ...,Hon A N Other,Hon A N Other,Plea,Mention date set (in court),NaN,12,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
3,2023-04-03,2023-04-03,QRCR/E638/2023,"Grievous harm, maim, assault causing actual bo...",Hon A N Other,Hon A N Other,Plea,Mention date set (in court),NaN,17,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
4,2023-04-03,2023-04-03,QRCRMISC/E109/2023,Criminal Miscellaneous Application,Hon A N Other,Hon A N Other,Certificate of urgency,Mention date set (in court),NaN,12,...,NaN,1,NaN,2,NaN,No,NaN,NaN,2,NaN

In [35]:
sample_data.drop(columns=["Judge 1"], inplace=True)

In [36]:
sample_data.head()

,Today's Date,Registration Date,Case Number,Specific Case Type,Judicial Officer,Case coming for,Case OutCome,Reason of adjournment,N-Day,N-Month,...,P-F,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details
0,2023-04-03,2023-04-03,QRCR/E642/2023,"Burglary, housebreaking, entering dwelling-hou...",Hon A N Other,Plea,Mention date set (in court),NaN,12,Apr,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
1,2023-04-03,2022-10-31,QRCR/E1411/2022,"Burglary, housebreaking, entering dwelling-hou...",Hon XYZ,Hearing,Adjournment,Advocate not ready,24,Apr,...,NaN,1,1,NaN,NaN,No,NaN,1,0,NaN
2,2023-04-03,2023-04-03,QRCR/E649/2023,Possession of narcotic drugs and psychotropic ...,Hon A N Other,Plea,Mention date set (in court),NaN,12,Apr,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
3,2023-04-03,2023-04-03,QRCR/E638/2023,"Grievous harm, maim, assault causing actual bo...",Hon A N Other,Plea,Mention date set (in court),NaN,17,Apr,...,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
4,2023-04-03,2023-04-03,QRCRMISC/E109/2023,Criminal Miscellaneous Application,Hon A N Other,Certificate of urgency,Mention date set (in court),NaN,12,Apr,...,NaN,1,NaN,2,NaN,No,NaN,NaN,2,NaN

In [37]:
sample_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2157 entries, 0 to 2156
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Today's Date           2157 non-null   datetime64[ns]
 1   Registration Date      2157 non-null   datetime64[ns]
 2   Case Number            2157 non-null   object
 3   Specific Case Type     2157 non-null   object
 4   Judicial Officer       2157 non-null   object
 5   Case coming for        2157 non-null   object
 6   Case OutCome           2157 non-null   object
 7   Reason of adjournment  156 non-null    object
 8   N-Day                  1639 non-null   object
 9   N-Month                1639 non-null   object
 10  N-Year                 1639 non-null   object
 11  P-M                    539 non-null    object
 12  P-F                    248 non-null    object
 13  P-Org.                 1425 non-null   object
 14  D-M                    1669 non-null   object
 15  D-F                    433 non-null    object
 16  D-Org.                 244 non-null    object
 17  Legal Rep              2157 non-null   object
 18  Witness-P              77 non-null     object
 19  Witness-D              25 non-null     object
 20  Crim-Custody           1697 non-null   object
 21  Other Details          506 non-null    object
dtypes: datetime64[ns](2), object(20)
memory usage: 370.9+ KB

In [38]:
sample_data["Next Date"] = sample_data["N-Day"].astype(str)+'-'+sample_data["N-Month"].astype(str)+'-'+sample_data["N-Year"].astype(str)

In [39]:
sample_data.head()

,Today's Date,Registration Date,Case Number,Specific Case Type,Judicial Officer,Case coming for,Case OutCome,Reason of adjournment,N-Day,N-Month,...,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details,Next Date
0,2023-04-03,2023-04-03,QRCR/E642/2023,"Burglary, housebreaking, entering dwelling-hou...",Hon A N Other,Plea,Mention date set (in court),NaN,12,Apr,...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,12-Apr-2023
1,2023-04-03,2022-10-31,QRCR/E1411/2022,"Burglary, housebreaking, entering dwelling-hou...",Hon XYZ,Hearing,Adjournment,Advocate not ready,24,Apr,...,1,1,NaN,NaN,No,NaN,1,0,NaN,24-Apr-2023
2,2023-04-03,2023-04-03,QRCR/E649/2023,Possession of narcotic drugs and psychotropic ...,Hon A N Other,Plea,Mention date set (in court),NaN,12,Apr,...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,12-Apr-2023
3,2023-04-03,2023-04-03,QRCR/E638/2023,"Grievous harm, maim, assault causing actual bo...",Hon A N Other,Plea,Mention date set (in court),NaN,17,Apr,...,1,1,NaN,NaN,No,NaN,NaN,1,NaN,17-Apr-2023
4,2023-04-03,2023-04-03,QRCRMISC/E109/2023,Criminal Miscellaneous Application,Hon A N Other,Certificate of urgency,Mention date set (in court),NaN,12,Apr,...,1,NaN,2,NaN,No,NaN,NaN,2,NaN,12-Apr-2023

In [40]:
# Convert to date
sample_data["Next Date"] = pd.to_datetime(sample_data["Next Date"], format='%d-%m-%Y')

ValueError: time data '12-Apr-2023' does not match format '%d-%m-%Y' (match)

In [41]:
# Convert to date
sample_data["Next Date"] = pd.to_datetime(sample_data["Next Date"], format='%d-%b-%Y')

ValueError: time data 'nan-nan-nan' does not match format '%d-%b-%Y' (match)

In [42]:
sample_data.drop(columns=["N-Day", "N-Month", "N-Year"], inplace=True)

In [43]:
sample_data.head()

,Today's Date,Registration Date,Case Number,Specific Case Type,Judicial Officer,Case coming for,Case OutCome,Reason of adjournment,P-M,P-F,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details,Next Date
0,2023-04-03,2023-04-03,QRCR/E642/2023,"Burglary, housebreaking, entering dwelling-hou...",Hon A N Other,Plea,Mention date set (in court),NaN,NaN,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN,12-Apr-2023
1,2023-04-03,2022-10-31,QRCR/E1411/2022,"Burglary, housebreaking, entering dwelling-hou...",Hon XYZ,Hearing,Adjournment,Advocate not ready,NaN,NaN,1,1,NaN,NaN,No,NaN,1,0,NaN,24-Apr-2023
2,2023-04-03,2023-04-03,QRCR/E649/2023,Possession of narcotic drugs and psychotropic ...,Hon A N Other,Plea,Mention date set (in court),NaN,NaN,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN,12-Apr-2023
3,2023-04-03,2023-04-03,QRCR/E638/2023,"Grievous harm, maim, assault causing actual bo...",Hon A N Other,Plea,Mention date set (in court),NaN,NaN,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN,17-Apr-2023
4,2023-04-03,2023-04-03,QRCRMISC/E109/2023,Criminal Miscellaneous Application,Hon A N Other,Certificate of urgency,Mention date set (in court),NaN,NaN,NaN,1,NaN,2,NaN,No,NaN,NaN,2,NaN,12-Apr-2023

In [44]:
sample_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2157 entries, 0 to 2156
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Today's Date           2157 non-null   datetime64[ns]
 1   Registration Date      2157 non-null   datetime64[ns]
 2   Case Number            2157 non-null   object
 3   Specific Case Type     2157 non-null   object
 4   Judicial Officer       2157 non-null   object
 5   Case coming for        2157 non-null   object
 6   Case OutCome           2157 non-null   object
 7   Reason of adjournment  156 non-null    object
 8   P-M                    539 non-null    object
 9   P-F                    248 non-null    object
 10  P-Org.                 1425 non-null   object
 11  D-M                    1669 non-null   object
 12  D-F                    433 non-null    object
 13  D-Org.                 244 non-null    object
 14  Legal Rep              2157 non-null   object
 15  Witness-P              77 non-null     object
 16  Witness-D              25 non-null     object
 17  Crim-Custody           1697 non-null   object
 18  Other Details          506 non-null    object
 19  Next Date              2157 non-null   object
dtypes: datetime64[ns](2), object(18)
memory usage: 337.2+ KB

In [45]:
sample_data.insert(8, "Next Date", sample_data.pop("Next Date"))

In [46]:
sample_data.head()

,Today's Date,Registration Date,Case Number,Specific Case Type,Judicial Officer,Case coming for,Case OutCome,Reason of adjournment,Next Date,P-M,P-F,P-Org.,D-M,D-F,D-Org.,Legal Rep,Witness-P,Witness-D,Crim-Custody,Other Details
0,2023-04-03,2023-04-03,QRCR/E642/2023,"Burglary, housebreaking, entering dwelling-hou...",Hon A N Other,Plea,Mention date set (in court),NaN,12-Apr-2023,NaN,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
1,2023-04-03,2022-10-31,QRCR/E1411/2022,"Burglary, housebreaking, entering dwelling-hou...",Hon XYZ,Hearing,Adjournment,Advocate not ready,24-Apr-2023,NaN,NaN,1,1,NaN,NaN,No,NaN,1,0,NaN
2,2023-04-03,2023-04-03,QRCR/E649/2023,Possession of narcotic drugs and psychotropic ...,Hon A N Other,Plea,Mention date set (in court),NaN,12-Apr-2023,NaN,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
3,2023-04-03,2023-04-03,QRCR/E638/2023,"Grievous harm, maim, assault causing actual bo...",Hon A N Other,Plea,Mention date set (in court),NaN,17-Apr-2023,NaN,NaN,1,1,NaN,NaN,No,NaN,NaN,1,NaN
4,2023-04-03,2023-04-03,QRCRMISC/E109/2023,Criminal Miscellaneous Application,Hon A N Other,Certificate of urgency,Mention date set (in court),NaN,12-Apr-2023,NaN,NaN,1,NaN,2,NaN,No,NaN,NaN,2,NaN

In [47]:
sample_data.isna().any()

Today's Date             False
Registration Date        False
Case Number              False
Specific Case Type       False
Judicial Officer         False
Case coming for          False
Case OutCome             False
Reason of adjournment     True
Next Date                False
P-M                       True
P-F                       True
P-Org.                    True
D-M                       True
D-F                       True
D-Org.                    True
Legal Rep                False
Witness-P                 True
Witness-D                 True
Crim-Custody              True
Other Details             True
dtype: bool